### ISSUE TITLE
Horizontally Aligned Radio label

### ISSUE THREAD

**Issue by garettarrowood** [powerhome/playbook#1476]
**Describe the solution you'd like**

Add a prop to the radio kit that allows each label to be responsively displayed horizontally to the right.

**Describe alternatives you've considered**

We got around this with custom JS/SCSS/Flex in the Nitro Survey domain. We needed centered text for desktop sizes. And vertically stacked/horizontal text for mobile sizes. Here is what we did.

```jsx
        <div className={style.opinionFlex}>
          {options.map(option => (
            <Field
                key={option.id}
                name={`${questionResponseName}.options`}
            >
              {({ field: { name, onChange }, form: { values } }) => (
                <Card
                    borderNone
                    className={style.optionCard}
                    padding="none"
                >
                  <Flex
                      align="center"
                      className={style.opinionScaleRadioContainer}
                      orientation={window.innerWidth <= 576 ? "row" : "column"}
                  >
                    <Radio
                        className={style.opinionScaleRadioButton}
                        error={errorMessage}
                        name={name}
                        onChange={onChange}
                        value={option.id}
                    />
                    <span className={style.opinionOptions}>{option.text}</span>
                  </Flex>
                </Card>
              )}
            </Field>
          ))}
        </div>
```

```scss
.opinionScaleRadioContainer {
  max-width: 45px;
}

.opinionScaleRadioButton {
  margin-right: 5px;
}

.opinionFlex {
  display: flex;
  flex-direction: row;
  justify-content: center;
  margin-top: 8px;

  @include break_at(breakpoint("sm")) {
    flex-direction: column;
    justify-content: left;
    margin-top: 8px;
  }
}

.opinionOptions {
  text-align: center;

  @include break_at(breakpoint("sm")) {
    white-space: nowrap
  }
}

.optionCard {
  margin-right: 40px;
  margin-left: 40px;

  @include break_at(breakpoint("sm")) {
    margin-left: 0px;
    margin-bottom: 15px;
  }
}
```

With a label display prop on the radio kit, this complexity might be reduced.
